import {useEffect,useState} from 'react';import {Link} from 'react-router-dom';import {Download,Share2,UserPlus} from 'lucide-react';import {api} from '../services/api';import {Badge,Loader,PageTitle} from '../components/UI';
const titleCase=(value='')=>String(value).toLowerCase().replace(/\b\w/g,ch=>ch.toUpperCase());
const sentenceCase=(value='')=>{const text=String(value).trim();return text?text.charAt(0).toUpperCase()+text.slice(1):''};
const formatAuditDateTime=(value)=>{
  if(!value)return {date:'—',time:'—'};
  const parsed=new Date(value);
  if(Number.isNaN(parsed.getTime())){
    const [datePart='',timePart='']=String(value).split('T');
    return {date:datePart||'—',time:(timePart.split('.')[0]||'—')};
  }
  return {
    date:parsed.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),
    time:parsed.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})
  };
};

export function Verifications(){const [rows,setRows]=useState(null);useEffect(()=>{api.candidates().then(setRows)},[]);if(!rows)return <Loader/>;return <><PageTitle title="Verifications" subtitle="Track Employment, Education, Identity And Document Verification."/><div className="verification-grid">{rows.map(c=><article className="panel" key={c.id}><div className="candidate-cell"><span>{c.name[0]}</span><div><h3>{c.name}</h3><small>{c.position}</small></div></div><div className="verify-list"><p>Employment <Badge value={c.employmentStatus}/></p><p>Education <Badge value={c.educationStatus}/></p><p>Identity <Badge value={c.identityStatus}/></p><p>Overall <Badge value={c.verificationStatus}/></p></div><Link className="btn secondary full" to={`/app/candidates/${c.id}`}>Review Candidate</Link></article>)}</div></>}
export function Reports(){const [rows,setRows]=useState(null);useEffect(()=>{api.candidates().then(setRows).catch(e=>{alert(e.message||'Unable To Load Reports.');setRows([])})},[]);if(!rows)return <Loader/>;const download=async c=>{try{const b=await api.report(c.id);const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=`CrossCheck-${c.name}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch(e){alert(e.message||'Unable To Download Report.')}};const share=async c=>{const shareData={title:'CrossCheck Report',text:`CrossCheck Report For ${c.name}`,url:`${window.location.origin}/app/candidates/${c.id}`};try{if(navigator.share){await navigator.share(shareData);return;}if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(shareData.url);alert('Candidate Report Link Copied.');return;}window.prompt('Copy This Candidate Report Link:',shareData.url)}catch(e){if(e?.name!=='AbortError')alert('Unable To Share This Report. Please Copy The Candidate Link Manually.')}};return <><PageTitle title="Reports" subtitle="Generate, Download And Share Complete Candidate Risk Reports."/><article className="panel table-panel"><div className="table-wrap"><table className="reports-table"><thead><tr><th>Candidate</th><th className="text-center">Risk Score</th><th className="text-center">Joining Probability</th><th className="text-center">Verification</th><th>Final Decision</th><th className="text-center">Actions</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><b>{c.name}</b><small className="block">{c.position}</small></td><td className="text-center"><b>{c.riskScore}/100</b></td><td className="text-center"><b>{c.joiningProbability}%</b></td><td className="text-center"><Badge value={c.verificationStatus}/></td><td>{c.aiRecommendation}</td><td className="text-center"><div className="actions centered-actions"><button type="button" title="Download PDF" onClick={()=>download(c)}><Download/></button><button type="button" title="Share" onClick={()=>share(c)}><Share2/></button></div></td></tr>)}</tbody></table></div></article></>}
export function Notifications(){const [rows,setRows]=useState(null);useEffect(()=>{api.notifications().then(setRows)},[]);if(!rows)return <Loader/>;return <><PageTitle title="Notifications" subtitle="Candidate, Verification, Risk And Report Events."/><div className="list-panel">{rows.map(n=>{const stamp=formatAuditDateTime(n.createdAt);return <article key={n.id || `${n.title}-${n.createdAt}`}><span className={`dot ${n.level?.toLowerCase()}`}></span><div><b>{titleCase(n.title)}</b><p>{sentenceCase(n.message)}</p><small className="notification-stamp"><span>{stamp.date}</span><span>{stamp.time}</span></small></div></article>})}</div></>}
export function Audit(){const [rows,setRows]=useState(null);useEffect(()=>{api.audits().then(setRows)},[]);if(!rows)return <Loader/>;return <><PageTitle title="Audit Logs" subtitle="A Secure History Of Important User And Candidate Actions."/><article className="panel table-panel"><div className="table-wrap"><table className="audit-table"><colgroup><col className="audit-user"/><col className="audit-action"/><col className="audit-entity"/><col className="audit-details"/><col className="audit-date"/><col className="audit-time"/></colgroup><thead><tr><th>User</th><th>Action</th><th>Entity</th><th>Details</th><th>Date</th><th>Time</th></tr></thead><tbody>{rows.map(a=>{const stamp=formatAuditDateTime(a.createdAt);return <tr key={a.id || `${a.userName}-${a.createdAt}`}><td>{a.userName}</td><td><Badge value={a.action}/></td><td>{a.entityType}</td><td>{a.details}</td><td>{stamp.date}</td><td>{stamp.time}</td></tr>})}</tbody></table></div></article></>}
export function Admin(){const [rows,setRows]=useState(null);const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [f,setF]=useState({name:'',email:'',password:'',role:'RECRUITER'});const load=()=>api.users().then(setRows).catch(e=>{alert(e.message||'Unable To Load Users.');setRows([])});useEffect(()=>{load()},[]);if(!rows)return <Loader/>;const add=async e=>{e.preventDefault();if(busy)return;setBusy(true);try{await api.createUser(f);setShow(false);setF({name:'',email:'',password:'',role:'RECRUITER'});await load()}catch(err){alert(err.message||'Unable To Create User.')}finally{setBusy(false)}};return <><PageTitle title="Admin Panel" subtitle="Manage Users, Roles, Permissions And Platform Configuration." action={<button type="button" className="btn" onClick={()=>setShow(!show)}><UserPlus/>{show?'Close':'Add User'}</button>}/>{show&&<form className="panel inline-form" onSubmit={add}><input required placeholder="Name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input required type="email" placeholder="Email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input required type="password" placeholder="Password" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/><select value={f.role} onChange={e=>setF({...f,role:e.target.value})}><option>RECRUITER</option><option>HR</option><option>ADMIN</option></select><button className="btn" disabled={busy}>{busy?'Creating…':'Create'}</button></form>}<div className="admin-cards"><article className="panel"><h3>Users & Roles</h3><p>{rows.length} Active Platform Users</p></article><article className="panel"><h3>Company</h3><p>CrossCheck Demo Organization</p></article><article className="panel"><h3>API Keys</h3><p>Verification Integrations Ready</p></article><article className="panel"><h3>Subscription</h3><p>Enterprise Plan</p></article></div><article className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{rows.map(u=><tr key={u.id || u.email}><td>{u.name}</td><td>{u.email}</td><td><Badge value={u.role}/></td><td><Badge value="ACTIVE"/></td></tr>)}</tbody></table></div></article></>}
